// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAHbltRA9TD-btQc3jqxBUJG9Us_Jgbu4g',
    appId: '1:1085873789627:web:d82ad872e399a0f28f279e',
    messagingSenderId: '1085873789627',
    projectId: 'flutter-notas-3capas-app',
    authDomain: 'flutter-notas-3capas-app.firebaseapp.com',
    storageBucket: 'flutter-notas-3capas-app.appspot.com',
    measurementId: 'G-Q1V8HDH4ZJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA69jNqxyFT0eW2DE30118QSX2tDo9_ovU',
    appId: '1:1085873789627:android:dc34272f250117b98f279e',
    messagingSenderId: '1085873789627',
    projectId: 'flutter-notas-3capas-app',
    storageBucket: 'flutter-notas-3capas-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBd002F_s0PVe8Rb6y9U4pIDAd7wKG2mBc',
    appId: '1:1085873789627:ios:5fa49c0fca1582528f279e',
    messagingSenderId: '1085873789627',
    projectId: 'flutter-notas-3capas-app',
    storageBucket: 'flutter-notas-3capas-app.appspot.com',
    iosBundleId: 'com.example.flutterNotas3capasApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBd002F_s0PVe8Rb6y9U4pIDAd7wKG2mBc',
    appId: '1:1085873789627:ios:c41391788a28ffeb8f279e',
    messagingSenderId: '1085873789627',
    projectId: 'flutter-notas-3capas-app',
    storageBucket: 'flutter-notas-3capas-app.appspot.com',
    iosBundleId: 'com.example.flutterNotas3capasApp.RunnerTests',
  );
}
